//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VisualStudio.BizTalkProject.Generators, Version 4.0.30319.42000.
// 
namespace FTPIssueTransfer.TransmitterRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TransmitterServiceSoapBinding", Namespace="http://www.bosch.com/edexas/asam/transmitter/services")]
    [Microsoft.XLANGs.BaseTypes.WebServiceUrlAttribute("http://si0vm595.de.bosch.com:18080/daimler-transmitter/services/TransmitterServic" +
        "ePort")]
    public partial class TransmitterService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public TransmitterService() {
            string urlSetting = System.Configuration.ConfigurationManager.AppSettings["FTPIssueTransfer.TransmitterRef.TransmitterService"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "");
            }
            else {
                this.Url = "http://si0vm595.de.bosch.com:18080/daimler-transmitter/services/TransmitterServic" +
                    "ePort";
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("transmitterResponse", Namespace="http://www.bosch.com/edexas/asam/transmitter/services")]
        public transmitterResponse startTransmit([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.bosch.com/edexas/asam/transmitter/services")] transmitterRequest transmitterRequest) {
            object[] results = this.Invoke("startTransmit", new object[] {
                        transmitterRequest});
            return ((transmitterResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginstartTransmit(transmitterRequest transmitterRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("startTransmit", new object[] {
                        transmitterRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public transmitterResponse EndstartTransmit(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((transmitterResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bosch.com/edexas/asam/transmitter/services")]
    public partial class transmitterRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] transferBinary;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string transferData;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string transferFile;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string transferType;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bosch.com/edexas/asam/transmitter/services")]
    public partial class transmitterResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public bool failure;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string result;
    }
}
